const carsDetails = [
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg/400px-2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg",
        "title": "Mazda MX-5",
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        "start_production": 1989,
        "class": "Sports car Roadster",
        "price": '10000',
        'id':'0'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VW_Kuebelwagen_1.jpg/400px-VW_Kuebelwagen_1.jpg",
        "title": "Volkswagen Kübelwagen",
        "class": "Military vehicle",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'1'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg/400px-2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg",
        "title": "Porsche Cayenne",
        "start_production": 2002,
        "class": "Mid-size luxury crossover SUV",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'2'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG/400px-Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG",
        "title": "Vauxhall Chevette",
        "start_production": 1975,
        "class": "Supermini",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'3'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg/400px-Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg",
        "title": "Dymaxion car",
        "start_production": 1933,
        "class": "Concept car",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'4'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg/400px-2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg",
        "title": "Mazda MX-5",
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        "start_production": 1989,
        "class": "Sports car Roadster",
        "price": '10000',
        'id':'5'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VW_Kuebelwagen_1.jpg/400px-VW_Kuebelwagen_1.jpg",
        "title": "Volkswagen Kübelwagen",
        "class": "Military vehicle",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'6'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg/400px-2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg",
        "title": "Porsche Cayenne",
        "start_production": 2002,
        "class": "Mid-size luxury crossover SUV",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'7'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG/400px-Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG",
        "title": "Vauxhall Chevette",
        "start_production": 1975,
        "class": "Supermini",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'8'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg/400px-Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg",
        "title": "Dymaxion car",
        "start_production": 1933,
        "class": "Concept car",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'9'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg/400px-2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg",
        "title": "Mazda MX-5",
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        "start_production": 1989,
        "class": "Sports car Roadster",
        "price": '10000',
        'id':'10'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VW_Kuebelwagen_1.jpg/400px-VW_Kuebelwagen_1.jpg",
        "title": "Volkswagen Kübelwagen",
        "class": "Military vehicle",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'11'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg/400px-2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg",
        "title": "Porsche Cayenne",
        "start_production": 2002,
        "class": "Mid-size luxury crossover SUV",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'12'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG/400px-Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG",
        "title": "Vauxhall Chevette",
        "start_production": 1975,
        "class": "Supermini",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'13'
    },
    {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg/400px-Dynamixion_car_by_Buckminster_Fuller_1933_%28side_views%29.jpg",
        "title": "Dymaxion car",
        "start_production": 1933,
        "class": "Concept car",
        "price": '10000',
        "year": "2012",
        "fuel_type": "Diesel",
        "seat": '4',
        'kms_driven': "40000",
        "mileage": "20",
        'max_power': '200',
        "engin": '300',
        'torque': '200',
        'color':'red',
        'id':'14'
    },
]

export default carsDetails;